   
export const POST_COMPLAINT = 'POST_COMPLAINT';     
export const GET_COMPLAINTS = 'GET_COMPLAINTS'; 
export const SET_COMPLAINT_FAIL = 'SET_COMPLAINT_FAIL';
export const GET_COMPLAINT_FAIL = 'GET_COMPLAINT_FAIL';
export const SET_COMPLAINT_SUCCESS = 'SET_COMPLAINT_SUCCESS';

export const POST_DOCUMENT = 'POST_DOCUMENT'; 
export const GET_USER_DOCUMENT = 'GET_USER_DOCUMENT'; 
export const GET_DOCUMENT_FAIL  = 'GET_DOCUMENT_FAIL';
export const POST_DOCUMENT_FAIL  = 'POST_DOCUMENT_FAIL';
export const POST_DOCUMENT_SUCCESS = 'POST_DOCUMENT_SUCCESS';

export const GET_EVENTS = 'GET_EVENTS'; 
export const SUCCESS_EVENT = 'SUCCESS_EVENT';
export const GET_EVENT_FAIL = 'GET_EVENT_FAIL';


export const GET_PERMITS = 'GET_PERMITS'; 
export const POST_PERMIT = 'POST_PERMIT'; 
export const GET_USER_PERMIT = 'GET_USER_PERMIT'; 
export const POST_PERMIT_FAIL  = 'POST_PERMIT_FAIL';
export const GET_FAIL_PERMIT = 'GET_FAIL_PERMIT';
export const SET_SUCCESS_PERMIT = 'SET_SUCCESS_PERMIT';

export const POST_USER = 'POST_USER'; 
export const GET_USER = 'GET_USER'; 
export const GET_FAIL_USER = 'GET_FAIL_USER';
export const GET_SUCCESS_USER = 'GET_SUCCESS_USER';
export const SET_SUCCESS_USER = 'SET_SUCCESS_USER';
export const SET_FAIL_USER = 'SET_FAIL_USER';
export const CONFIRM_SIGN_UP = 'CONFIRM_SIGN_UP'; 

export const SIGN_IN_USER = 'SIGN_IN_USER'; 
export const SIGN_IN_USER_FAIL = 'SIGN_IN_USER_FAIL';

